# Generated by Django 5.1rc1 on 2024-08-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('popular_products', 'Popular Products Report'), ('average_orders', 'Average Orders Report'), ('average_ratings', 'Average Ratings Report')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
