# Generated by Django 5.1rc1 on 2024-07-31 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_product_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 31, 10, 40, 34, 726646, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 31, 10, 40, 34, 726646, tzinfo=datetime.timezone.utc)),
        ),
    ]
