# Generated by Django 5.1rc1 on 2024-08-05 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_telephone_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 5, 12, 22, 3, 987421, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 5, 12, 22, 3, 987421, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Оформлен'), ('In Progress', 'В работе'), ('Delivering', 'Доставляется'), ('Completed', 'Завершен')], default='Ordered', max_length=20),
        ),
    ]
