# Generated by Django 5.1rc1 on 2024-07-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_category_parent_category_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Описание отсутствует'),
        ),
    ]
